name: Format & Lint & Type Check & Test & Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: ðŸ§ Format
        run: deno fmt --check
      - name: ðŸ§ Lint
        run: deno lint
      - name: ðŸ§ Type Check
        run: deno test --no-run ./dev/typecheck.ts & true
      - name: ðŸ§ Test
        run: deno test --allow-run --allow-net --allow-read --unstable --coverage=coverage
      - name: Create coverage report
        run: deno coverage ./coverage --lcov > coverage.lcov
      - name: llllll
        run: cat ./coverage.lcov
      - name: Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          file: ./coverage.lcov
          fail_ci_if_error: true
